name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - heroku
  pull_request:
    branches:
      - heroku

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter --version
      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: 'Build Web App'
        run: flutter build web
      - name: 'Deploy to Firebase Hosting'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: 'Deploy to Heroku'
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "meloncloud-app" #Must be unique in Heroku
          heroku_email: "melondev@icloud.com"
